### ISSUE TITLE
Article search questions

### ISSUE THREAD

**Issue by jwee-star** [crcaorui/Model-Constrained-Deep-Learning-for-Online-Fault-Diagnosis#1]
hi, I can't find this article"Model Constrained Deep Learning for Online Fault Diagnosis in Li-ion Batteries over Stochastic Conditions", 
has it been published or has a pre-print version?thanks

**Comment by jwee-star** [comment]
and where can find the dataset description？If I could receive your reply, I would be extremely grateful

**Comment by crcaorui** [comment]
Hello, this article is currently under review. The detailed information of the dataset is still being organized and will be updated within the next 30 days~










-----原始邮件-----
发件人:jwee-star ***@***.***>
发送时间:2024-08-23 15:06:29 (星期五)
收件人: crcaorui/Model-Constrained-Deep-Learning-for-Online-Fault-Diagnosis ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [crcaorui/Model-Constrained-Deep-Learning-for-Online-Fault-Diagnosis] Article search questions (Issue #1)






and where can find the dataset description？If I could receive your reply, I would be extremely grateful

**Comment by jwee-star** [comment]
> Hello, this article is currently under review. The detailed information of the dataset is still being organized and will be updated within the next 30 days~
> […](#)
> -----原始邮件----- 发件人:jwee-star ***@***.***> 发送时间:2024-08-23 15:06:29 (星期五) 收件人: crcaorui/Model-Constrained-Deep-Learning-for-Online-Fault-Diagnosis ***@***.***> 抄送: Subscribed ***@***.***> 主题: Re: [crcaorui/Model-Constrained-Deep-Learning-for-Online-Fault-Diagnosis] Article search questions (Issue #1) and where can find the dataset description？If I could receive your reply, I would be extremely grateful — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
Got it, Looking forward to your publication, best wishes to you~
